#### iOS 设备名称 转换 ####
def ios_real_device device
  case self.device
  when "iPod1,1"
    return "iPod Touch"
  when "iPod2,1"
    return "iPod Touch 2"
  when "iPod3,1"
    return "iPod Touch 3"
  when "iPod4,1"
    return "iPod Touch 4"
  when "iPod5,1"
    return "iPod Touch 5"
  when "iPhone1,1"
    return "iPhone"
  when "iPhone1,2"
    return "iPhone 3G"
  when "iPhone2,1"
    return "iPhone 3GS"
  when "iPhone3,1", "iPhone3,2", "iPhone3,3"
    return "iPhone 4"
  when "iPhone4,1"
    return "iPhone 4S"
  when "iPhone5,1", "iPhone5,2"
    return "iPhone 5"
  when "iPhone5,3", "iPhone5,4"
    return "iPhone 5c"
  when "iPhone6,1", "iPhone6,2"
    return "iPhone 5s"
  when "iPad1,1"
    return "iPad"
  when "iPad2,1", "iPad2,2", "iPad2,3", "iPad2,4"
    return "iPad 2"
  when "iPad3,1", "iPad3,2", "iPad3,3"
    return "iPad 3"
  when "iPad3,4", "iPad3,5", "iPad3,6"
    return "iPad 4"
  when "iPad2,5", "iPad2,6", "iPad2,7"
    return "iPad Mini"
  when "iPad4,1", "iPad4,2"
    return "iPad Air"
  when "iPad4,4", "iPad4,5"
    return "iPad mini 2"
  else
    return self.device
  end
end